package com.codeguardian.service.agent;

public enum ReviewAgentWorkflow {
    AGENT_WORKFLOW_STARTED,
    STATIC_SCAN_COMPLETED,
    AGENT_PLAN_CREATED,
    AGENT_RAG_RETRIEVED,
    REVIEWER_DRAFT_CREATED,
    AGENT_FINDING_CANDIDATE_CREATED,
    AGENT_FINDING_CHALLENGED,
    AGENT_FINDING_ACCEPTED,
    AGENT_FINDING_REJECTED,
    AGENT_FINDING_DOWNGRADED,
    AGENT_DEBATE_ACTION_SELECTED,
    AGENT_DEBATE_LOOP_COMPLETED,
    JUDGE_DECISION_CREATED,
    AGENT_FINDING_REVISED,
    DETERMINISTIC_VERIFICATION_COMPLETED,
    FINAL_FINDINGS_SAVED,
    AGENT_WORKFLOW_COMPLETED,
    AGENT_WORKFLOW_FAILED
}
